volumes:
  dotnest-sqlserver-data:

networks:
  dotnest:
  dotnest-database:

services:

  dotnest-nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    networks:
      - dotnest

  dotnest:
    extends:
      file: DotNest/docker-compose.yml
      service: dotnest
    depends_on:
      - dotnest-sqlserver
    environment:
      ConnectionStrings__SqlServer: Data Source=sqlserver,1433;Database=master;User Id=sa;Password=Yourpassword123;TrustServerCertificate=True;
    networks:
      - dotnest
      - dotnest-database

  dotnest-sqlserver:
    extends:
      file: Database/docker-compose.yml
      service: dotnest-sqlserver
    networks:
      - dotnest-database
