volumes:
  sqlserver-data:

networks:
  dotnest:
  dotnest-database:

services:

  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    networks:
      - dotnest
    ports:
      - 8080:80

  dotnest:
    extends:
      file: DotNest/docker-compose.yml
      service: dotnest
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__SqlServer: Server=sqlserver,1433;Database=DotNestDB;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
    networks:
      - dotnest
      - dotnest-database

  sqlserver:
    extends:
      file: Database/docker-compose.yml
      service: sqlserver
    networks:
      - dotnest-database
    ports:
      - 1433:1433
