volumes:
  dotnest-sqlserver-data:
  dotnest-postgres-data:

networks:
  dotnest:
  dotnest-database:

services:

  dotnest-nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    networks:
      - dotnest
    depends_on:
      - dotnest

  dotnest:
    extends:
      file: DotNest/docker-compose.yml
      service: dotnest
    depends_on:
      - dotnest-postgres
    environment:
      ConnectionStrings__Postgres: Host=dotnest-postgres;Port=5432;Database=dotnest;Username=dotnest;Password=yourpassword123
    networks:
      - dotnest
      - dotnest-database

  dotnest-postgres:
    extends:
      file: Database/docker-compose.yml
      service: dotnest-postgres
    networks:
      - dotnest-database
