volumes:
  dotnest-sqlserver-data:
  dotnest-postgres-data:

networks:
  dotnest:
  dotnest-database:

services:

  dotnest-nginx:
    extends:
      file: docker-compose.yml
      service: dotnest-nginx
    ports:
      - 8080:80
    depends_on:
      - dotnest

  dotnest:
    extends:
      file: docker-compose.yml
      service: dotnest
    depends_on:
      - dotnest-postgres

  dotnest-postgres:
    extends:
      file: docker-compose.yml
      service: dotnest-postgres
    ports:
      - 5432:5432
