volumes:
  sqlserver-data:

services:
  sqlserver:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "1433"
    environment:
      SA_PASSWORD: "Yourpassword123"
    volumes:
      - sqlserver-data:/var/opt/mssql
