volumes:
  sqlserver-data:

services:
  sqlserver:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "1433"
    environment:
      SA_PASSWORD: "Your_password123"
    volumes:
      - ./Database/dbo/Tables:/sql-init:ro
      - sqlserver-data:/var/opt/mssql
