volumes:
  dotnest-sqlserver-data:

services:
  dotnest-sqlserver:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "1433"
    environment:
      SA_PASSWORD: "Yourpassword123"
    volumes:
      - dotnest-sqlserver-data:/var/opt/mssql
