volumes:
  dotnest-sqlserver-data:
  dotnest-postgres-data:

services:
  dotnest-sqlserver:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "1433"
    environment:
      SA_PASSWORD: "Yourpassword123"
    volumes:
      - dotnest-sqlserver-data:/var/opt/mssql
    profiles:
      - "sqlserver"

  dotnest-postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: dotnest
      POSTGRES_PASSWORD: yourpassword123
      POSTGRES_DB: dotnest
    expose:
      - 5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - dotnest-postgres-data:/var/lib/postgresql/data
